//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
// 
namespace AWSClient.ACSWebService {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MyServiceSoap", Namespace="MyServiceNameSpace")]
    public class MyService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public MyService() {
            this.Url = "http://localhost/ACSWebService/MyService.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("MyServiceNameSpace/Method1", RequestNamespace="MyServiceNameSpace", ResponseNamespace="MyServiceNameSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Method1(int val) {
            object[] results = this.Invoke("Method1", new object[] {
                        val});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginMethod1(int val, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Method1", new object[] {
                        val}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndMethod1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
    }
}
