// ACOMComp.idl : IDL source for ACOMComp
//

// This file will be processed by the MIDL tool to
// produce the type library (ACOMComp.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(1D972698-B69E-48DF-90CB-3258410F48B6),
	dual,
	nonextensible,
	helpstring("IMyComp Interface"),
	pointer_default(unique)
]
interface IMyComp : IDispatch{
	[id(1), helpstring("method doSomething")] HRESULT doSomething([out] int* pCount);
};
[
	uuid(06B486A8-F271-4932-A9BE-F2E12E011A7D),
	version(1.0),
	helpstring("ACOMComp 1.0 Type Library")
]
library ACOMCompLib
{
	importlib("stdole2.tlb");
	[
		uuid(E4EB3427-1E60-4EEC-9C6F-3A82F707DE13),
		helpstring("MyComp Class")
	]
	coclass MyComp
	{
		[default] interface IMyComp;
	};
};
